const WS_URL="wss://ws.binaryws.com/websockets/v3";
const state={ws:null,symbol:null,tf:300,candles:[],tick:null,req:0,symbols:[]};
const $=id=>document.getElementById(id);
const els={symbol:$("symbol"),price:$("price"),updated:$("updated"),signal:$("signal"),confidence:$("confidence"),trend:$("trend"),momentum:$("momentum"),rsi:$("rsi"),atr:$("atr"),resistance:$("resistance"),support:$("support"),entry:$("entry"),reason:$("reason"),invalidation:$("invalidation"),tp1:$("tp1"),tp2:$("tp2"),tp3:$("tp3"),risk:$("risk"),chart:$("chart"),marketTitle:$("marketTitle"),tfTitle:$("tfTitle"),signalCard:$("signalCard"),connection:$("connection")};
function send(p){if(state.ws?.readyState===1)state.ws.send(JSON.stringify({...p,req_id:++state.req}))}
function connect(){if(state.ws)try{state.ws.close()}catch{}state.ws=new WebSocket(WS_URL);state.ws.onopen=()=>{els.connection.className="status live";els.connection.innerHTML="<span></span> DERIV LIVE";send({active_symbols:"brief",product_type:"basic"})};state.ws.onclose=()=>{els.connection.className="status";els.connection.innerHTML="<span></span> DISCONNECTED";setTimeout(connect,2500)};state.ws.onerror=()=>{els.connection.className="status error";els.connection.innerHTML="<span></span> CONNECTION ERROR"};state.ws.onmessage=e=>handle(JSON.parse(e.data))}
function handle(d){if(d.msg_type==="active_symbols"){state.symbols=d.active_symbols||[];const preferred=state.symbols.find(s=>/gold|xau/i.test((s.display_name||"")+" "+(s.symbol||"")))||state.symbols.find(s=>/usd/i.test(s.symbol||""));els.symbol.innerHTML=state.symbols.filter(s=>s.symbol).map(s=>'<option value="'+esc(s.symbol)+'">'+esc(s.display_name||s.symbol)+'</option>').join("");if(preferred)els.symbol.value=preferred.symbol;load()}if(d.msg_type==="candles"){state.candles=(d.candles||[]).map(c=>({t:+c.epoch,o:+c.open,h:+c.high,l:+c.low,c:+c.close}));analyze();draw()}if(d.msg_type==="tick"&&d.tick){state.tick=+d.tick.quote;els.price.textContent=fmt(state.tick);els.updated.textContent=new Date(d.tick.epoch*1000).toLocaleTimeString();if(state.candles.length)draw()}}
function load(){state.symbol=els.symbol.value;if(!state.symbol)return;state.candles=[];send({ticks_history:state.symbol,end:"latest",count:180,style:"candles",granularity:state.tf,subscribe:1});send({ticks:state.symbol,subscribe:1});const s=state.symbols.find(x=>x.symbol===state.symbol);els.marketTitle.textContent=s?.display_name||state.symbol;els.tfTitle.textContent=tfName(state.tf)}
function tfName(v){return({300:"M5",900:"M15",3600:"H1",14400:"H4"})[v]||String(v)+"s"}
function fmt(v){return Number(v).toLocaleString(undefined,{maximumFractionDigits:5})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function ema(a,n){if(!a.length)return 0;const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const x=a[i]-a[i-1];if(x>=0)g+=x;else l-=x}if(l===0)return 100;const rs=(g/n)/(l/n);return 100-(100/(1+rs))}
function atr(cs,n=14){if(cs.length<n+1)return 0;const tr=[];for(let i=1;i<cs.length;i++)tr.push(Math.max(cs[i].h-cs[i].l,Math.abs(cs[i].h-cs[i-1].c),Math.abs(cs[i].l-cs[i-1].c)));return tr.slice(-n).reduce((a,b)=>a+b,0)/Math.min(n,tr.length)}
function levels(cs){const recent=cs.slice(-40);return{res:Math.max(...recent.map(x=>x.h)),sup:Math.min(...recent.map(x=>x.l))}}
function analyze(){const cs=state.candles;if(cs.length<30)return;const closes=cs.map(x=>x.c),price=state.tick||closes.at(-1),e9=ema(closes.slice(-80),9),e21=ema(closes.slice(-80),21),e50=ema(closes.slice(-100),50),R=rsi(closes),A=atr(cs),lv=levels(cs),slope=closes.at(-1)-closes[Math.max(0,closes.length-8)];const bullish=e9>e21&&e21>e50&&slope>0,bearish=e9<e21&&e21<e50&&slope<0;let sig="WAIT",why="Structure is mixed. Wait for clearer confirmation.";if(bullish&&R<72&&price<lv.res+A*.35){sig="BUY";why="Short-term trend is bullish with price above the EMA stack and positive momentum. A pullback/retest is preferable to chasing the current candle."}else if(bearish&&R>28&&price>lv.sup+A*.35){sig="SELL";why="Short-term trend is bearish with price below the EMA stack and negative momentum. A retest/rejection is preferable to chasing the move."}else if(R>=72)why="Momentum is extended to the upside. Waiting for a pullback or fresh breakout confirmation.";else if(R<=28)why="Momentum is extended to the downside. Waiting for a pullback or fresh breakdown confirmation.";const buffer=A*.65,entry=sig==="BUY"?[price-buffer*.5,price+buffer*.15]:sig==="SELL"?[price-buffer*.15,price+buffer*.5]:[Math.min(lv.sup+buffer,price),Math.max(lv.res-buffer,price)],inv=sig==="BUY"?price-buffer:sig==="SELL"?price+buffer:price,dir=sig==="SELL"?-1:1;els.signal.textContent=sig;els.signalCard.className="signal-card panel "+sig.toLowerCase();els.confidence.textContent="Structure: "+(bullish?"bullish":bearish?"bearish":"mixed")+" · RSI "+R.toFixed(1);els.trend.textContent=bullish?"BULLISH":bearish?"BEARISH":"MIXED";els.momentum.textContent=slope>0?"POSITIVE":"NEGATIVE";els.rsi.textContent=R.toFixed(1);els.atr.textContent=fmt(A);els.resistance.textContent=fmt(lv.res);els.support.textContent=fmt(lv.sup);els.entry.textContent=fmt(entry[0])+" – "+fmt(entry[1]);els.invalidation.textContent=sig==="WAIT"?"—":fmt(inv);els.tp1.textContent=sig==="WAIT"?"—":fmt(price+dir*A);els.tp2.textContent=sig==="WAIT"?"—":fmt(price+dir*A*1.8);els.tp3.textContent=sig==="WAIT"?"—":fmt(price+dir*A*2.6);els.reason.textContent=why;els.risk.textContent="RISK: "+((Math.abs(price-(sig==="BUY"?lv.res:lv.sup))/Math.max(A,1e-9)<1)?"ELEVATED — near level":"NORMAL")}
function draw(){const c=els.chart,ctx=c.getContext("2d"),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);const cs=state.candles.slice(-70);if(!cs.length)return;const min=Math.min(...cs.map(x=>x.l)),max=Math.max(...cs.map(x=>x.h)),pad=(max-min)*.08||1,lo=min-pad,hi=max+pad,x=i=>18+i*(w-36)/Math.max(cs.length-1,1),y=p=>h-20-(p-lo)/(hi-lo)*(h-35);ctx.strokeStyle="#172630";ctx.lineWidth=1;for(let i=0;i<6;i++){const yy=18+i*(h-38)/5;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}cs.forEach((q,i)=>{const xx=x(i),cw=Math.max(3,(w-45)/cs.length*.62);ctx.strokeStyle=q.c>=q.o?"#3eb6a4":"#df6969";ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(q.h));ctx.lineTo(xx,y(q.l));ctx.stroke();const top=y(Math.max(q.o,q.c)),bot=y(Math.min(q.o,q.c));ctx.fillRect(xx-cw/2,top,cw,Math.max(1,bot-top))});if(state.tick){ctx.strokeStyle="#6f8290";ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(0,y(state.tick));ctx.lineTo(w,y(state.tick));ctx.stroke();ctx.setLineDash([])}}
document.querySelectorAll("#timeframes button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#timeframes button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tf=+b.dataset.tf;load()});els.symbol.onchange=load;$("refresh").onclick=load;window.addEventListener("resize",draw);connect();
